title: No Fly Zone
encoding: UTF-8
url: "https://vingkan.github.io/noflyzone"
baseurl: "/noflyzone"
markdown: kramdown
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

collections:
  clues:
    output: true

game:
  # Express the game start time in minutes, other clues will add
  # minutes relative to this point and display it in clock time.
  # 6:30 PM = (12 * 60) + (6 * 60) + 30 = 1110
  startminutes: 1110

defaults:
  - scope:
      path: ""
      type: "clues"
    values:
      layout: "clue"
